# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.manejo_de_archivos.protos_convertidor_de_archivos import ConvertidorDeArchivos_pb2 as app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/manejo_de_archivos/protos_convertidor_de_archivos/ConvertidorDeArchivos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConvertidorDeCancionesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertirCancionAMP3 = channel.stream_stream(
                '/convertidor_de_archivos.ConvertidorDeCanciones/ConvertirCancionAMP3',
                request_serializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirCancion.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaCancionesConvertidas.FromString,
                _registered_method=True)


class ConvertidorDeCancionesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertirCancionAMP3(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConvertidorDeCancionesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertirCancionAMP3': grpc.stream_stream_rpc_method_handler(
                    servicer.ConvertirCancionAMP3,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirCancion.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaCancionesConvertidas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'convertidor_de_archivos.ConvertidorDeCanciones', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('convertidor_de_archivos.ConvertidorDeCanciones', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConvertidorDeCanciones(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertirCancionAMP3(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/convertidor_de_archivos.ConvertidorDeCanciones/ConvertirCancionAMP3',
            app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirCancion.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaCancionesConvertidas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConvertidorDeImagenesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertirImagenAPng = channel.stream_stream(
                '/convertidor_de_archivos.ConvertidorDeImagenes/ConvertirImagenAPng',
                request_serializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirPortada.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaImagenesConvertidas.FromString,
                _registered_method=True)


class ConvertidorDeImagenesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConvertirImagenAPng(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConvertidorDeImagenesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertirImagenAPng': grpc.stream_stream_rpc_method_handler(
                    servicer.ConvertirImagenAPng,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirPortada.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaImagenesConvertidas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'convertidor_de_archivos.ConvertidorDeImagenes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('convertidor_de_archivos.ConvertidorDeImagenes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConvertidorDeImagenes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConvertirImagenAPng(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/convertidor_de_archivos.ConvertidorDeImagenes/ConvertirImagenAPng',
            app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.SolicitudConvertirPortada.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos__convertidor__de__archivos_dot_ConvertidorDeArchivos__pb2.RespuestaImagenesConvertidas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
