# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.manejo_de_archivos.protos import ManejadorDeArchivos_pb2 as app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/manejo_de_archivos/protos/ManejadorDeArchivos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CancionesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubirCancionPersonal = channel.stream_unary(
                '/manejador_de_archivos.Canciones/SubirCancionPersonal',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                _registered_method=True)
        self.SubirCancion = channel.stream_unary(
                '/manejador_de_archivos.Canciones/SubirCancion',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                _registered_method=True)
        self.ObtenerCancion = channel.unary_stream(
                '/manejador_de_archivos.Canciones/ObtenerCancion',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
                _registered_method=True)
        self.ObtenerCancionPersonal = channel.unary_stream(
                '/manejador_de_archivos.Canciones/ObtenerCancionPersonal',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
                _registered_method=True)


class CancionesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubirCancionPersonal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirCancion(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCancion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerCancionPersonal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CancionesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubirCancionPersonal': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirCancionPersonal,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'SubirCancion': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirCancion,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'ObtenerCancion': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerCancion,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.SerializeToString,
            ),
            'ObtenerCancionPersonal': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerCancionPersonal,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manejador_de_archivos.Canciones', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manejador_de_archivos.Canciones', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Canciones(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubirCancionPersonal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/manejador_de_archivos.Canciones/SubirCancionPersonal',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubirCancion(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/manejador_de_archivos.Canciones/SubirCancion',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirCancion.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCancion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/manejador_de_archivos.Canciones/ObtenerCancion',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerCancionPersonal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/manejador_de_archivos.Canciones/ObtenerCancionPersonal',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerCancion.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerCancion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PortadasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubirPortadaAlbum = channel.stream_unary(
                '/manejador_de_archivos.Portadas/SubirPortadaAlbum',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                _registered_method=True)
        self.SubirPortadaCreadorDeContenido = channel.stream_unary(
                '/manejador_de_archivos.Portadas/SubirPortadaCreadorDeContenido',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                _registered_method=True)
        self.SubirPortadaUsuario = channel.stream_unary(
                '/manejador_de_archivos.Portadas/SubirPortadaUsuario',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
                _registered_method=True)
        self.ObtenerPortadaAlbum = channel.unary_stream(
                '/manejador_de_archivos.Portadas/ObtenerPortadaAlbum',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
                _registered_method=True)
        self.ObtenerPortadaCreadorDeContenido = channel.unary_stream(
                '/manejador_de_archivos.Portadas/ObtenerPortadaCreadorDeContenido',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
                _registered_method=True)
        self.ObtenerPortadaUsuario = channel.unary_stream(
                '/manejador_de_archivos.Portadas/ObtenerPortadaUsuario',
                request_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
                response_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
                _registered_method=True)


class PortadasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubirPortadaAlbum(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirPortadaCreadorDeContenido(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubirPortadaUsuario(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerPortadaAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerPortadaCreadorDeContenido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerPortadaUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortadasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubirPortadaAlbum': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirPortadaAlbum,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'SubirPortadaCreadorDeContenido': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirPortadaCreadorDeContenido,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'SubirPortadaUsuario': grpc.stream_unary_rpc_method_handler(
                    servicer.SubirPortadaUsuario,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.SerializeToString,
            ),
            'ObtenerPortadaAlbum': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerPortadaAlbum,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.SerializeToString,
            ),
            'ObtenerPortadaCreadorDeContenido': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerPortadaCreadorDeContenido,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.SerializeToString,
            ),
            'ObtenerPortadaUsuario': grpc.unary_stream_rpc_method_handler(
                    servicer.ObtenerPortadaUsuario,
                    request_deserializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.FromString,
                    response_serializer=app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manejador_de_archivos.Portadas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manejador_de_archivos.Portadas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Portadas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubirPortadaAlbum(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/manejador_de_archivos.Portadas/SubirPortadaAlbum',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubirPortadaCreadorDeContenido(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/manejador_de_archivos.Portadas/SubirPortadaCreadorDeContenido',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubirPortadaUsuario(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/manejador_de_archivos.Portadas/SubirPortadaUsuario',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudSubirPortada.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaSolicitudSubirArchivo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerPortadaAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/manejador_de_archivos.Portadas/ObtenerPortadaAlbum',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerPortadaCreadorDeContenido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/manejador_de_archivos.Portadas/ObtenerPortadaCreadorDeContenido',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerPortadaUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/manejador_de_archivos.Portadas/ObtenerPortadaUsuario',
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.SolicitudObtenerPortada.SerializeToString,
            app_dot_manejo__de__archivos_dot_protos_dot_ManejadorDeArchivos__pb2.RespuestaObtenerPortada.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
